# ==============================================================================
# Automated Inventory Generated by Terraform (DO NOT EDIT MANUALLY)
# Dynamic Multi-Role / Multi-Group Inventory
# ==============================================================================
all:
  vars:
    ansible_user: ${ssh_username}
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  children:
%{ for role in distinct([for k, vm in vms : vm.role if vm.role != null && vm.role != ""]) ~}
    ${role}:
      hosts:
%{ for k, vm in vms ~}
%{ if vm.role == role ~}
        ${vm.name}:
          ansible_host: ${vm.ip_address}
%{ if vm.vm_id != null ~}
          node_id: ${vm.vm_id}
%{ endif ~}
          node_role: ${vm.role}
%{ endif ~}
%{ endfor ~}

%{ endfor ~}
    all_nodes:
      hosts:
%{ for k, vm in vms ~}
        ${vm.name}:
          ansible_host: ${vm.ip_address}
%{ if vm.vm_id != null ~}
          node_id: ${vm.vm_id}
%{ endif ~}
          node_role: ${vm.role != null ? vm.role : "generic"}
%{ endfor ~}
