# ==============================================================================
# Automated Inventory Generated by Terraform (DO NOT EDIT MANUALLY)
# Target Environment: Lab vSphere Cluster
# ==============================================================================
all:
  vars:
    ansible_user: ${ssh_username}
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519

  children:
    elastic_cluster:
      hosts:
%{ for k, vm in vms ~}
%{ if vm.role == "master_data_ingest" ~}
        ${vm.name}:
          ansible_host: ${vm.ip_address}
          node_id: ${vm.vm_id}
          node_role: ${vm.role}
%{ endif ~}
%{ endfor ~}

    kibana_gateway:
      hosts:
%{ for k, vm in vms ~}
%{ if vm.role == "kibana_fleet_gateway" ~}
        ${vm.name}:
          ansible_host: ${vm.ip_address}
          node_id: ${vm.vm_id}
          node_role: gateway
%{ endif ~}
%{ endfor ~}

    fleet_server:
      children:
        kibana_gateway:

    elastic_agent:
      children:
        kibana_gateway:

    monitored_nodes:
      children:
        elastic_cluster:
