all:
  vars:
    ansible_user: svc_admin

  children:
    elastic_cluster:
      hosts:
        srv-elastic-01:
          ansible_host: 10.255.242.211
          node_id: 101
          node_role: master_data_ingest
        srv-elastic-02:
          ansible_host: 10.255.242.212
          node_id: 102
          node_role: master_data_ingest
        srv-elastic-03:
          ansible_host: 10.255.242.213
          node_id: 103
          node_role: master_data_ingest

    kibana_gateway:
      hosts:
        srv-kibana-gw:
          ansible_host: 10.255.242.214
          node_id: 104
          node_role: gateway

    fleet_server:
      children:
        kibana_gateway

    elastic_agent:
      children:
        kibana_gateway

    monitored_nodes:
      children:
        elastic_cluster
